steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud run deploy hello-world-service --source . --allow-unauthenticated --region us-central1']
timeout: '1600s'
